use crate::cpu::AddressingMode;
use std::collections::HashMap;
use once_cell::sync::Lazy;


#[derive(Debug)]
pub enum Mnemonic {
    ADC, AND, ASL, BCC, BCS, BEQ, BIT, BMI, BNE, BPL, BRK, BVC, BVS, CLC,
    CLD, CLI, CLV, CMP, CPX, CPY, DEC, DEX, DEY, EOR, INC, INX, INY, JMP,
    JSR, LDA, LDX, LDY, LSR, NOP, ORA, PHA, PHP, PLA, PLP, ROL, ROR, RTI,
    RTS, SBC, SEC, SED, SEI, STA, STX, STY, TAX, TAY, TSX, TXA, TXS, TYA,
    SHY, STP, SHX, SLO, RLA, SRE, RRA, SAX, LAX, DCP, ISC, ANC, ALR, ARR,
    XAA, AHX, AXS, TAS, LAS,
}

pub struct OpCode {
    pub code: u8,
    pub mnemonic: Mnemonic,
    pub mode: AddressingMode,
    pub bytes: u8,
    pub cycles: u8,
}

impl OpCode {
    const fn new(code: u8, mnemonic: Mnemonic, mode: AddressingMode, bytes: u8, cycles: u8) -> OpCode {
        OpCode { code, mnemonic, mode, bytes, cycles }
    }
}


pub static OPCODES_MAP: Lazy<HashMap<u8, &OpCode>> = Lazy::new(|| {
    OPCODES.iter().map(|op| (op.code, op)).collect()
});


const OPCODES: [OpCode; 256] = [
    // Control Instructions
    OpCode::new(0x00, Mnemonic::BRK, AddressingMode::Implicit, 1, 7),
    OpCode::new(0x04, Mnemonic::NOP, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x08, Mnemonic::PHP, AddressingMode::Implicit, 1, 3),
    OpCode::new(0x0C, Mnemonic::NOP, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x10, Mnemonic::BPL, AddressingMode::Relative, 2, 2),
    OpCode::new(0x14, Mnemonic::NOP, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x18, Mnemonic::CLC, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x1C, Mnemonic::NOP, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0x20, Mnemonic::JSR, AddressingMode::Absolute, 3, 6),
    OpCode::new(0x24, Mnemonic::BIT, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x28, Mnemonic::PLP, AddressingMode::Implicit, 1, 4),
    OpCode::new(0x2C, Mnemonic::BIT, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x30, Mnemonic::BMI, AddressingMode::Relative, 2, 2),
    OpCode::new(0x34, Mnemonic::NOP, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x38, Mnemonic::SEC, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x3C, Mnemonic::NOP, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0x40, Mnemonic::RTI, AddressingMode::Implicit, 1, 6),
    OpCode::new(0x44, Mnemonic::NOP, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x48, Mnemonic::PHA, AddressingMode::Implicit, 1, 3),
    OpCode::new(0x4C, Mnemonic::JMP, AddressingMode::Absolute, 3, 3),
    OpCode::new(0x50, Mnemonic::BVC, AddressingMode::Relative, 2, 2),
    OpCode::new(0x54, Mnemonic::NOP, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x58, Mnemonic::CLI, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x5C, Mnemonic::NOP, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0x60, Mnemonic::RTS, AddressingMode::Implicit, 1, 6),
    OpCode::new(0x64, Mnemonic::NOP, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x68, Mnemonic::PLA, AddressingMode::Implicit, 1, 4),
    OpCode::new(0x6C, Mnemonic::JMP, AddressingMode::Indirect, 3, 5),
    OpCode::new(0x70, Mnemonic::BVS, AddressingMode::Relative, 2, 2),
    OpCode::new(0x74, Mnemonic::NOP, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x78, Mnemonic::SEI, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x7C, Mnemonic::NOP, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0x80, Mnemonic::NOP, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x84, Mnemonic::STY, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x88, Mnemonic::DEY, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x8C, Mnemonic::STY, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x90, Mnemonic::BCC, AddressingMode::Relative, 2, 2),
    OpCode::new(0x94, Mnemonic::STY, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x98, Mnemonic::TYA, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x9C, Mnemonic::SHY, AddressingMode::Absolute_X, 3, 5),

    OpCode::new(0xA0, Mnemonic::LDY, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xA4, Mnemonic::LDY, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0xA8, Mnemonic::TAY, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xAC, Mnemonic::LDY, AddressingMode::Absolute, 3, 4),
    OpCode::new(0xB0, Mnemonic::BCS, AddressingMode::Relative, 2, 2),
    OpCode::new(0xB4, Mnemonic::LDY, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0xB8, Mnemonic::CLV, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xBC, Mnemonic::LDY, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0xC0, Mnemonic::CPY, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xC4, Mnemonic::CPY, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0xC8, Mnemonic::INY, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xCC, Mnemonic::CPY, AddressingMode::Absolute, 3, 4),
    OpCode::new(0xD0, Mnemonic::BNE, AddressingMode::Relative, 2, 2),
    OpCode::new(0xD4, Mnemonic::NOP, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0xD8, Mnemonic::CLD, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xDC, Mnemonic::NOP, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0xE0, Mnemonic::CPX, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xE4, Mnemonic::CPX, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0xE8, Mnemonic::INX, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xEC, Mnemonic::CPX, AddressingMode::Absolute, 3, 4),
    OpCode::new(0xF0, Mnemonic::BEQ, AddressingMode::Relative, 2, 2),
    OpCode::new(0xF4, Mnemonic::NOP, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0xF8, Mnemonic::SED, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xFC, Mnemonic::NOP, AddressingMode::Absolute_X, 3, 4),


    // ALU operations
    OpCode::new(0x01, Mnemonic::ORA, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0x05, Mnemonic::ORA, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x09, Mnemonic::ORA, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x0D, Mnemonic::ORA, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x11, Mnemonic::ORA, AddressingMode::Indirect_Y, 2, 5),
    OpCode::new(0x15, Mnemonic::ORA, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x19, Mnemonic::ORA, AddressingMode::Absolute_Y, 3, 4),
    OpCode::new(0x1D, Mnemonic::ORA, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0x21, Mnemonic::AND, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0x25, Mnemonic::AND, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x29, Mnemonic::AND, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x2D, Mnemonic::AND, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x31, Mnemonic::AND, AddressingMode::Indirect_Y, 2, 5),
    OpCode::new(0x35, Mnemonic::AND, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x39, Mnemonic::AND, AddressingMode::Absolute_Y, 3, 4),
    OpCode::new(0x3D, Mnemonic::AND, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0x41, Mnemonic::EOR, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0x45, Mnemonic::EOR, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x49, Mnemonic::EOR, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x4D, Mnemonic::EOR, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x51, Mnemonic::EOR, AddressingMode::Indirect_Y, 2, 5),
    OpCode::new(0x55, Mnemonic::EOR, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x59, Mnemonic::EOR, AddressingMode::Absolute_Y, 3, 4),
    OpCode::new(0x5D, Mnemonic::EOR, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0x61, Mnemonic::ADC, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0x65, Mnemonic::ADC, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x69, Mnemonic::ADC, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x6D, Mnemonic::ADC, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x71, Mnemonic::ADC, AddressingMode::Indirect_Y, 2, 5),
    OpCode::new(0x75, Mnemonic::ADC, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x79, Mnemonic::ADC, AddressingMode::Absolute_Y, 3, 4),
    OpCode::new(0x7D, Mnemonic::ADC, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0x81, Mnemonic::STA, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0x85, Mnemonic::STA, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x89, Mnemonic::NOP, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x8D, Mnemonic::STA, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x91, Mnemonic::STA, AddressingMode::Indirect_Y, 2, 6),
    OpCode::new(0x95, Mnemonic::STA, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0x99, Mnemonic::STA, AddressingMode::Absolute_Y, 3, 5),
    OpCode::new(0x9D, Mnemonic::STA, AddressingMode::Absolute_X, 3, 5),

    OpCode::new(0xA1, Mnemonic::LDA, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0xA5, Mnemonic::LDA, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0xA9, Mnemonic::LDA, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xAD, Mnemonic::LDA, AddressingMode::Absolute, 3, 4),
    OpCode::new(0xB1, Mnemonic::LDA, AddressingMode::Indirect_Y, 2, 5),
    OpCode::new(0xB5, Mnemonic::LDA, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0xB9, Mnemonic::LDA, AddressingMode::Absolute_Y, 3, 4),
    OpCode::new(0xBD, Mnemonic::LDA, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0xC1, Mnemonic::CMP, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0xC5, Mnemonic::CMP, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0xC9, Mnemonic::CMP, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xCD, Mnemonic::CMP, AddressingMode::Absolute, 3, 4),
    OpCode::new(0xD1, Mnemonic::CMP, AddressingMode::Indirect_Y, 2, 5),
    OpCode::new(0xD5, Mnemonic::CMP, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0xD9, Mnemonic::CMP, AddressingMode::Absolute_Y, 3, 4),
    OpCode::new(0xDD, Mnemonic::CMP, AddressingMode::Absolute_X, 3, 4),

    OpCode::new(0xE1, Mnemonic::SBC, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0xE5, Mnemonic::SBC, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0xE9, Mnemonic::SBC, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xED, Mnemonic::SBC, AddressingMode::Absolute, 3, 4),
    OpCode::new(0xF1, Mnemonic::SBC, AddressingMode::Indirect_Y, 2, 5),
    OpCode::new(0xF5, Mnemonic::SBC, AddressingMode::ZeroPage_X, 2, 4),
    OpCode::new(0xF9, Mnemonic::SBC, AddressingMode::Absolute_Y, 3, 4),
    OpCode::new(0xFD, Mnemonic::SBC, AddressingMode::Absolute_X, 3, 4),


    // RMW operations
    OpCode::new(0x02, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x06, Mnemonic::ASL, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0x0A, Mnemonic::ASL, AddressingMode::Accumulator, 1, 2),
    OpCode::new(0x0E, Mnemonic::ASL, AddressingMode::Absolute, 3, 6),
    OpCode::new(0x12, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x16, Mnemonic::ASL, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0x1A, Mnemonic::NOP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x1E, Mnemonic::ASL, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0x22, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x26, Mnemonic::ROL, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0x2A, Mnemonic::ROL, AddressingMode::Accumulator, 1, 2),
    OpCode::new(0x2E, Mnemonic::ROL, AddressingMode::Absolute, 3, 6),
    OpCode::new(0x32, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x36, Mnemonic::ROL, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0x3A, Mnemonic::NOP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x3E, Mnemonic::ROL, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0x42, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x46, Mnemonic::LSR, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0x4A, Mnemonic::LSR, AddressingMode::Accumulator, 1, 2),
    OpCode::new(0x4E, Mnemonic::LSR, AddressingMode::Absolute, 3, 6),
    OpCode::new(0x52, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x56, Mnemonic::LSR, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0x5A, Mnemonic::NOP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x5E, Mnemonic::LSR, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0x62, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x66, Mnemonic::ROR, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0x6A, Mnemonic::ROR, AddressingMode::Accumulator, 1, 2),
    OpCode::new(0x6E, Mnemonic::ROR, AddressingMode::Absolute, 3, 6),
    OpCode::new(0x72, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x76, Mnemonic::ROR, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0x7A, Mnemonic::NOP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x7E, Mnemonic::ROR, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0x82, Mnemonic::NOP, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x86, Mnemonic::STX, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x8A, Mnemonic::TXA, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x8E, Mnemonic::STX, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x92, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x96, Mnemonic::STX, AddressingMode::ZeroPage_Y, 2, 4),
    OpCode::new(0x9A, Mnemonic::TXS, AddressingMode::Implicit, 1, 2),
    OpCode::new(0x9E, Mnemonic::SHX, AddressingMode::Absolute_Y, 3, 5),

    OpCode::new(0xA2, Mnemonic::LDX, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xA6, Mnemonic::LDX, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0xAA, Mnemonic::TAX, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xAE, Mnemonic::LDX, AddressingMode::Absolute, 3, 4),
    OpCode::new(0xB2, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xB6, Mnemonic::LDX, AddressingMode::ZeroPage_Y, 2, 4),
    OpCode::new(0xBA, Mnemonic::TSX, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xBE, Mnemonic::LDX, AddressingMode::Absolute_Y, 3, 4),

    OpCode::new(0xC2, Mnemonic::NOP, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xC6, Mnemonic::DEC, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0xCA, Mnemonic::DEX, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xCE, Mnemonic::DEC, AddressingMode::Absolute, 3, 6),
    OpCode::new(0xD2, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xD6, Mnemonic::DEC, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0xDA, Mnemonic::NOP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xDE, Mnemonic::DEC, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0xE2, Mnemonic::NOP, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xE6, Mnemonic::INC, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0xEA, Mnemonic::NOP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xEE, Mnemonic::INC, AddressingMode::Absolute, 3, 6),
    OpCode::new(0xF2, Mnemonic::STP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xF6, Mnemonic::INC, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0xFA, Mnemonic::NOP, AddressingMode::Implicit, 1, 2),
    OpCode::new(0xFE, Mnemonic::INC, AddressingMode::Absolute_X, 3, 7),


    // Other unofficial instruments
    OpCode::new(0x03, Mnemonic::SLO, AddressingMode::Indirect_X, 2, 8),
    OpCode::new(0x07, Mnemonic::SLO, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0x0B, Mnemonic::ANC, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x0F, Mnemonic::SLO, AddressingMode::Absolute, 3, 6),
    OpCode::new(0x13, Mnemonic::SLO, AddressingMode::Indirect_Y, 2, 8),
    OpCode::new(0x17, Mnemonic::SLO, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0x1B, Mnemonic::SLO, AddressingMode::Absolute_Y, 3, 7),
    OpCode::new(0x1F, Mnemonic::SLO, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0x23, Mnemonic::RLA, AddressingMode::Indirect_X, 2, 8),
    OpCode::new(0x27, Mnemonic::RLA, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0x2B, Mnemonic::ANC, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x2F, Mnemonic::RLA, AddressingMode::Absolute, 3, 6),
    OpCode::new(0x33, Mnemonic::RLA, AddressingMode::Indirect_Y, 2, 8),
    OpCode::new(0x37, Mnemonic::RLA, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0x3B, Mnemonic::RLA, AddressingMode::Absolute_Y, 3, 7),
    OpCode::new(0x3F, Mnemonic::RLA, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0x43, Mnemonic::SRE, AddressingMode::Indirect_X, 2, 8),
    OpCode::new(0x47, Mnemonic::SRE, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0x4B, Mnemonic::ALR, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x4F, Mnemonic::SRE, AddressingMode::Absolute, 3, 6),
    OpCode::new(0x53, Mnemonic::SRE, AddressingMode::Indirect_Y, 2, 8),
    OpCode::new(0x57, Mnemonic::SRE, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0x5B, Mnemonic::SRE, AddressingMode::Absolute_Y, 3, 7),
    OpCode::new(0x5F, Mnemonic::SRE, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0x63, Mnemonic::RRA, AddressingMode::Indirect_X, 2, 8),
    OpCode::new(0x67, Mnemonic::RRA, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0x6B, Mnemonic::ARR, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x6F, Mnemonic::RRA, AddressingMode::Absolute, 3, 6),
    OpCode::new(0x73, Mnemonic::RRA, AddressingMode::Indirect_Y, 2, 8),
    OpCode::new(0x77, Mnemonic::RRA, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0x7B, Mnemonic::RRA, AddressingMode::Absolute_Y, 3, 7),
    OpCode::new(0x7F, Mnemonic::RRA, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0x83, Mnemonic::SAX, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0x87, Mnemonic::SAX, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0x8B, Mnemonic::XAA, AddressingMode::Immediate, 2, 2),
    OpCode::new(0x8F, Mnemonic::SAX, AddressingMode::Absolute, 3, 4),
    OpCode::new(0x93, Mnemonic::AHX, AddressingMode::Indirect_Y, 2, 6),
    OpCode::new(0x97, Mnemonic::SAX, AddressingMode::ZeroPage_Y, 2, 4),
    OpCode::new(0x9B, Mnemonic::TAS, AddressingMode::Absolute_Y, 3, 5),
    OpCode::new(0x9F, Mnemonic::AHX, AddressingMode::Absolute_Y, 3, 5),

    OpCode::new(0xA3, Mnemonic::LAX, AddressingMode::Indirect_X, 2, 6),
    OpCode::new(0xA7, Mnemonic::LAX, AddressingMode::ZeroPage, 2, 3),
    OpCode::new(0xAB, Mnemonic::LAX, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xAF, Mnemonic::LAX, AddressingMode::Absolute, 3, 4),
    OpCode::new(0xB3, Mnemonic::LAX, AddressingMode::Indirect_Y, 2, 5),
    OpCode::new(0xB7, Mnemonic::LAX, AddressingMode::ZeroPage_Y, 2, 4),
    OpCode::new(0xBB, Mnemonic::LAS, AddressingMode::Absolute_Y, 3, 4),
    OpCode::new(0xBF, Mnemonic::LAX, AddressingMode::Absolute_Y, 3, 4),

    OpCode::new(0xC3, Mnemonic::DCP, AddressingMode::Indirect_X, 2, 8),
    OpCode::new(0xC7, Mnemonic::DCP, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0xCB, Mnemonic::AXS, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xCF, Mnemonic::DCP, AddressingMode::Absolute, 3, 6),
    OpCode::new(0xD3, Mnemonic::DCP, AddressingMode::Indirect_Y, 2, 8),
    OpCode::new(0xD7, Mnemonic::DCP, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0xDB, Mnemonic::DCP, AddressingMode::Absolute_Y, 3, 7),
    OpCode::new(0xDF, Mnemonic::DCP, AddressingMode::Absolute_X, 3, 7),

    OpCode::new(0xE3, Mnemonic::ISC, AddressingMode::Indirect_X, 2, 8),
    OpCode::new(0xE7, Mnemonic::ISC, AddressingMode::ZeroPage, 2, 5),
    OpCode::new(0xEB, Mnemonic::SBC, AddressingMode::Immediate, 2, 2),
    OpCode::new(0xEF, Mnemonic::ISC, AddressingMode::Absolute, 3, 6),
    OpCode::new(0xF3, Mnemonic::ISC, AddressingMode::Indirect_Y, 2, 8),
    OpCode::new(0xF7, Mnemonic::ISC, AddressingMode::ZeroPage_X, 2, 6),
    OpCode::new(0xFB, Mnemonic::ISC, AddressingMode::Absolute_Y, 3, 7),
    OpCode::new(0xFF, Mnemonic::ISC, AddressingMode::Absolute_X, 3, 7),
];
